# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
    - master
    paths:
      - "build.gradle"
      - "gradle.properties"
      - "src/**"  
  pull_request:
    branches:
    - master
    paths:
      - "build.gradle"
      - "gradle.properties"
      - "src/**"


jobs:
  properties:
    runs-on: ubuntu-latest
    outputs:
      mod-version: ${{ steps.properties.outputs.mod_version }}
      mc-version: ${{ steps.properties.outputs.minecraft_version }}
      fabric-version: ${{ steps.properties.outputs.fabric_version }}
      yarn-version: ${{ steps.properties.outputs.yarn_version }}
      fabric-api-version: ${{ steps.properties.outputs.fabric_api_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Read relevant fields from gradle.properties
        id: properties
        run: | # From christian-draeger/read-properties, using the action makes it extremely messy until christian-draeger/read-properties#2
          path='./gradle.properties'
          for property in mod_version minecraft_version yarn_version fabric_version fabric_api_version
          do
            result=$(sed -n "/^[[:space:]]*$property[[:space:]]*=[[:space:]]*/s/^[[:space:]]*$property[[:space:]]*=[[:space:]]*//p" "$path")
            echo "$property: $result"
            echo ::set-output name=$property::"$result"
          done
  build:
    runs-on: ubuntu-latest
    needs: [properties]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Display build number
      run: echo Build number \#$GITHUB_RUN_NUMBER
    - name: Set build number in codes
      run: |
        sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties
        sed -i "s/musername/${{ secrets.MAVEN_USERNAME }}/g" gradle.properties
        sed -i "s/mpassword/${{ secrets.MAVEN_PASSWORD }}/g" gradle.properties
    - name: Give permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/
    - name: publish to maven
      run: ./gradlew publish
